# run skyland.py
name: Auto Sign

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run skyland.py
        env:
          GitHub_Actions: true
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Token 长度: ${#TOKEN}"
          echo "Token 前4位: ${TOKEN:0:4}"
          printf "3\n%s\n" "$TOKEN" | python skyland.py
